
-- ==============================================================================
-- SCRIPT DE INICIALIZACIÓN SUPABASE - PROYECTO: NOTIFICAPE
-- Dialecto: PostgreSQL
-- Nota: Se usan comillas dobles ("") para forzar el PascalCase/CamelCase
-- requerido por la convención del Developer.
-- ==============================================================================

-- 1. EXTENSIONES
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==========================================
-- 2. CATÁLOGOS BASE
-- ==========================================

CREATE TABLE public."Licencias" (
    "IdLicencia" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Nombre" VARCHAR(50) NOT NULL,
    "LimiteDispositivos" INT DEFAULT 1,
    "LimiteUsuarios" INT NOT NULL,
    "PrecioCentimos" INT NOT NULL,
    "Moneda" VARCHAR(3) DEFAULT 'PEN',
    "DuracionDias" INT NOT NULL DEFAULT 30,
    "SkuExterno" VARCHAR(50) UNIQUE NOT NULL,
    "Activo" BOOLEAN DEFAULT TRUE
);

CREATE TABLE public."Billeteras" (
    "IdBilletera" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PackageName" VARCHAR(100) UNIQUE NOT NULL,
    "Nombre" VARCHAR(50) NOT NULL
);

CREATE TABLE public."EstadosAuth" (
    "IdEstadoAuth" SMALLINT PRIMARY KEY,
    "NomEstaAuth" VARCHAR(20) NOT NULL
);

CREATE TABLE public."Roles" (
    "IdRol" SMALLINT PRIMARY KEY,
    "NomRol" VARCHAR(20) NOT NULL,
    "CanRead" BOOLEAN NOT NULL,
    "CanWrite" BOOLEAN NOT NULL
);

CREATE TABLE public."FiltrosXBilletera" (
    "IdFiltroBil" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IdBilletera" SMALLINT REFERENCES public."Billeteras"("IdBilletera") ON DELETE CASCADE,
    "NombreRegla" VARCHAR(50) NOT NULL,
    "RegexContenido" TEXT NOT NULL
);

-- ==========================================
-- 3. IDENTIDAD Y AUDITORÍA DE COMPRAS
-- ==========================================

CREATE TABLE public."Contratantes" (
    "IdContratante" UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    "NombreCompleto" VARCHAR(150) NOT NULL,
    "NombreNegocio" VARCHAR(100),
    "Correo" VARCHAR(100) UNIQUE NOT NULL,
    "TelefonoContratante" VARCHAR(20),
    "FechaCreacion" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public."Usuarios" (
    "IdUsuario" UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    "IdRol" SMALLINT REFERENCES public."Roles"("IdRol"),
    "NombreCompleto" VARCHAR(150) NOT NULL,
    "Correo" VARCHAR(100) UNIQUE NOT NULL,
    "TelefonoUsuario" VARCHAR(20),
    "EquipoMarca" VARCHAR(50),
    "EquipoModelo" VARCHAR(50),
    "FechaCreacion" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public."OrdenesCompra" (
    "NumeroOrden" VARCHAR(50) PRIMARY KEY,
    "PlataformaOrigen" VARCHAR(50) NOT NULL,
    "IdContratante" UUID REFERENCES public."Contratantes"("IdContratante") ON DELETE CASCADE,
    "FechaCanje" TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 4. INVENTARIO PREPAGO
-- ==========================================

CREATE TABLE public."LicenciasXContratante" (
    "IdLicenciaContratante" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IdContratante" UUID REFERENCES public."Contratantes"("IdContratante") ON DELETE CASCADE,
    "IdLicencia" SMALLINT REFERENCES public."Licencias"("IdLicencia"),
    "NumeroOrden" VARCHAR(50) REFERENCES public."OrdenesCompra"("NumeroOrden"),
    "DispositivoAsignado" UUID, -- NULL = Disponible en inventario
    "FechaAsignacion" TIMESTAMPTZ
);

-- ==========================================
-- 5. HARDWARE Y CONFIGURACIÓN
-- ==========================================

CREATE TABLE public."DispositivosXContratante" (
    "IdDispositivo" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "HardwareId" VARCHAR(100) UNIQUE,
    "IdContratante" UUID REFERENCES public."Contratantes"("IdContratante") ON DELETE CASCADE,
    "IdLicencia" SMALLINT REFERENCES public."Licencias"("IdLicencia"),
    "AliasDispositivo" VARCHAR(50) NOT NULL,
    "CodigoAcceso" VARCHAR(10) UNIQUE NOT NULL,
    "EquipoMarca" VARCHAR(50),
    "EquipoModelo" VARCHAR(50),
    "TelefonoDispositivo" VARCHAR(20),
    "FechaVencimiento" TIMESTAMPTZ, -- Permitimos NULL inicial
    "IsConnected" BOOLEAN DEFAULT FALSE,
    "Activo" BOOLEAN DEFAULT TRUE,
    "FechaReg" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public."BilleterasXDispositivo" (
    "IdDispositivo" UUID REFERENCES public."DispositivosXContratante"("IdDispositivo") ON DELETE CASCADE,
    "IdBilletera" SMALLINT REFERENCES public."Billeteras"("IdBilletera") ON DELETE CASCADE,
    "UrlQrPago" VARCHAR(255),
    "Activo" BOOLEAN DEFAULT TRUE,
    PRIMARY KEY ("IdDispositivo", "IdBilletera")
);

-- ==========================================
-- 6. AUTORIZACIÓN Y TRANSACCIONALIDAD
-- ==========================================

CREATE TABLE public."AutorizacionesXUsuario" (
    "IdAutorizacion" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IdDispositivo" UUID REFERENCES public."DispositivosXContratante"("IdDispositivo") ON DELETE CASCADE,
    "IdUsuario" UUID REFERENCES public."Usuarios"("IdUsuario") ON DELETE CASCADE,
    "IdEstadoAuth" SMALLINT REFERENCES public."EstadosAuth"("IdEstadoAuth"),
    "FechRegist" TIMESTAMPTZ DEFAULT NOW(),
    "IsConnected" BOOLEAN DEFAULT FALSE,
    "Observacion" VARCHAR(255)
);

CREATE TABLE public."NotificacionesXDispositivo" (
    "IdSync" UUID PRIMARY KEY,
    "SecuenciaLocal" BIGINT GENERATED ALWAYS AS IDENTITY,
    "IdDispositivo" UUID REFERENCES public."DispositivosXContratante"("IdDispositivo") ON DELETE CASCADE,
    "IdContratante" UUID REFERENCES public."Contratantes"("IdContratante") ON DELETE CASCADE,
    "IdBilletera" SMALLINT REFERENCES public."Billeteras"("IdBilletera"),
    "ContenidoMsg" VARCHAR(500) NOT NULL,
    "MontoCentimos" INT NOT NULL,
    "Moneda" VARCHAR(3) DEFAULT 'PEN',
    "Remitente" VARCHAR(100),
    "Privada" BOOLEAN DEFAULT FALSE,
    "Prueba" BOOLEAN DEFAULT FALSE,
    "FechaOpera" TIMESTAMPTZ NOT NULL,
    "EstadoProgreso" VARCHAR(20) DEFAULT 'PENDIENTE', -- PENDIENTE, REVISION, COMPLETADO, CERRADO
    "ContadorReclamaciones" INT DEFAULT 0,
    "IdUsuarioGanador" UUID REFERENCES public."Usuarios"("IdUsuario")
);

CREATE TABLE public."NotificacionesAUsuarios" (
    "IdSync" UUID REFERENCES public."NotificacionesXDispositivo"("IdSync") ON DELETE CASCADE,
    "IdUsuario" UUID REFERENCES public."Usuarios"("IdUsuario"),
    "FechaReg" TIMESTAMPTZ DEFAULT NOW(),
    "Observacion" TEXT,
    "EstadoReclamacion" VARCHAR(20) DEFAULT 'PROCESANDO',
    PRIMARY KEY ("IdSync", "IdUsuario")
);

-- ==========================================
-- 7. ÍNDICES DE RENDIMIENTO (B-TREE)
-- ==========================================

CREATE INDEX "idx_notif_caja_diaria" ON public."NotificacionesXDispositivo" ("IdDispositivo", "FechaOpera" DESC);
CREATE INDEX "idx_notif_reporte_gerencial" ON public."NotificacionesXDispositivo" ("IdContratante", "FechaOpera" DESC);

-- ==========================================
-- 8. CUMPLIMIENTO LEGAL Y SEGURIDAD
-- ==========================================

CREATE TABLE public."Superadministradores" (
    "IdSuperadmin" UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    "Correo" VARCHAR(100) UNIQUE NOT NULL,
    "FechaCreacion" TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TABLE public."Reclamaciones" (
    "IdReclamacion" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "CodigoReclamacion" VARCHAR(50) UNIQUE,
    "IdContratante" UUID REFERENCES public."Contratantes"("IdContratante") ON DELETE SET NULL,
    "NombreCompleto" VARCHAR(150) NOT NULL,
    "TipoDocumento" VARCHAR(20) NOT NULL,
    "NumeroDocumento" VARCHAR(20) NOT NULL,
    "Correo" VARCHAR(100) NOT NULL,
    "Telefono" VARCHAR(20) NOT NULL,
    "TipoReclamacion" VARCHAR(20) NOT NULL,
    "DetalleReclamacion" TEXT NOT NULL,
    "PedidoCliente" TEXT NOT NULL,
    "Estado" VARCHAR(20) DEFAULT 'PENDIENTE' NOT NULL,
    "Respuesta" TEXT,
    "FechaRegistro" TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    "FechaRespuesta" TIMESTAMPTZ
);
-- Script: 0031_superadmin_fixes.sql
-- App Origen: NotificaPe_Specs / db
-- Autor: AGENT_ROLE (Orquestador SDD / Arquitecto Principal)
-- Fecha: 2026-07-18
-- Justificación: Políticas RLS para Superadministradores para acceder a Dispositivos, Crédito y Notificaciones sin afectar usuarios normales. Función RPC para ajuste de créditos.

BEGIN;

-- 1. Políticas RLS para Superadministradores (Lectura Extendida y Update Acotado)

-- A. DispositivosXContratante
DROP POLICY IF EXISTS "Superadmin_Read_Dispositivos" ON public."DispositivosXContratante";
CREATE POLICY "Superadmin_Read_Dispositivos" ON public."DispositivosXContratante"
FOR SELECT USING (EXISTS (SELECT 1 FROM public."Superadministradores" WHERE "IdSuperadmin" = auth.uid()));

DROP POLICY IF EXISTS "Superadmin_Update_Dispositivos" ON public."DispositivosXContratante";
CREATE POLICY "Superadmin_Update_Dispositivos" ON public."DispositivosXContratante"
FOR UPDATE USING (EXISTS (SELECT 1 FROM public."Superadministradores" WHERE "IdSuperadmin" = auth.uid()))
WITH CHECK (EXISTS (SELECT 1 FROM public."Superadministradores" WHERE "IdSuperadmin" = auth.uid()));

-- B. CreditoXContratante
DROP POLICY IF EXISTS "Superadmin_Read_Credito" ON public."CreditoXContratante";
CREATE POLICY "Superadmin_Read_Credito" ON public."CreditoXContratante"
FOR SELECT USING (EXISTS (SELECT 1 FROM public."Superadministradores" WHERE "IdSuperadmin" = auth.uid()));

-- C. NotificacionesXDispositivo (Depurador Regex y Limpieza Spam)
DROP POLICY IF EXISTS "Superadmin_Read_Notificaciones" ON public."NotificacionesXDispositivo";
CREATE POLICY "Superadmin_Read_Notificaciones" ON public."NotificacionesXDispositivo"
FOR SELECT USING (EXISTS (SELECT 1 FROM public."Superadministradores" WHERE "IdSuperadmin" = auth.uid()));

DROP POLICY IF EXISTS "Superadmin_Update_Notificaciones" ON public."NotificacionesXDispositivo";
CREATE POLICY "Superadmin_Update_Notificaciones" ON public."NotificacionesXDispositivo"
FOR UPDATE USING (EXISTS (SELECT 1 FROM public."Superadministradores" WHERE "IdSuperadmin" = auth.uid()))
WITH CHECK (EXISTS (SELECT 1 FROM public."Superadministradores" WHERE "IdSuperadmin" = auth.uid()));

-- D. LicenciasCola
DROP POLICY IF EXISTS "Superadmin_Read_LicenciasCola" ON public."LicenciasCola";
CREATE POLICY "Superadmin_Read_LicenciasCola" ON public."LicenciasCola"
FOR SELECT USING (EXISTS (SELECT 1 FROM public."Superadministradores" WHERE "IdSuperadmin" = auth.uid()));

DROP POLICY IF EXISTS "Superadmin_Update_LicenciasCola" ON public."LicenciasCola";
CREATE POLICY "Superadmin_Update_LicenciasCola" ON public."LicenciasCola"
FOR UPDATE USING (EXISTS (SELECT 1 FROM public."Superadministradores" WHERE "IdSuperadmin" = auth.uid()))
WITH CHECK (EXISTS (SELECT 1 FROM public."Superadministradores" WHERE "IdSuperadmin" = auth.uid()));

DROP POLICY IF EXISTS "Superadmin_Delete_LicenciasCola" ON public."LicenciasCola";
CREATE POLICY "Superadmin_Delete_LicenciasCola" ON public."LicenciasCola"
FOR DELETE USING (EXISTS (SELECT 1 FROM public."Superadministradores" WHERE "IdSuperadmin" = auth.uid()));

-- E. Billeteras y FiltrosXBilletera (Permisos de gestión CRUD para Superadmin)
ALTER TABLE public."Billeteras" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public_Read_Billeteras" ON public."Billeteras";
CREATE POLICY "Public_Read_Billeteras" ON public."Billeteras" FOR SELECT USING (true);
DROP POLICY IF EXISTS "Superadmin_All_Billeteras" ON public."Billeteras";
CREATE POLICY "Superadmin_All_Billeteras" ON public."Billeteras"
FOR ALL USING (EXISTS (SELECT 1 FROM public."Superadministradores" WHERE "IdSuperadmin" = auth.uid()))
WITH CHECK (EXISTS (SELECT 1 FROM public."Superadministradores" WHERE "IdSuperadmin" = auth.uid()));

ALTER TABLE public."FiltrosXBilletera" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public_Read_Filtros" ON public."FiltrosXBilletera";
CREATE POLICY "Public_Read_Filtros" ON public."FiltrosXBilletera" FOR SELECT USING (true);
DROP POLICY IF EXISTS "Superadmin_All_Filtros" ON public."FiltrosXBilletera";
CREATE POLICY "Superadmin_All_Filtros" ON public."FiltrosXBilletera"
FOR ALL USING (EXISTS (SELECT 1 FROM public."Superadministradores" WHERE "IdSuperadmin" = auth.uid()))
WITH CHECK (EXISTS (SELECT 1 FROM public."Superadministradores" WHERE "IdSuperadmin" = auth.uid()));

-- F. Contratantes (Leer a todos los contratantes para el listado)
DROP POLICY IF EXISTS "Superadmin_Read_Contratantes" ON public."Contratantes";
CREATE POLICY "Superadmin_Read_Contratantes" ON public."Contratantes"
FOR SELECT USING (EXISTS (SELECT 1 FROM public."Superadministradores" WHERE "IdSuperadmin" = auth.uid()));


-- 2. RPC: ajustar_credito_superadmin
-- Propósito: Modificar el saldo del contratante (sumar o restar) dejando rastro de auditoría y sin activar licencias.

CREATE OR REPLACE FUNCTION public.ajustar_credito_superadmin(
    p_id_contratante UUID,
    p_monto_ajuste BIGINT, -- Positivo (abono) o Negativo (cargo)
    p_moneda CHAR(3) DEFAULT 'PEN'
) RETURNS BOOLEAN AS $$
DECLARE
    v_es_superadmin BOOLEAN;
    v_tipo_movimiento TEXT;
    v_monto_absoluto BIGINT;
    v_saldo_actual BIGINT;
BEGIN
    -- Validar permisos de Superadmin
    SELECT EXISTS (
        SELECT 1 FROM public."Superadministradores" WHERE "IdSuperadmin" = auth.uid()
    ) INTO v_es_superadmin;
    
    IF NOT v_es_superadmin THEN
        RAISE EXCEPTION 'Acceso denegado. Solo un superadministrador puede ejecutar esta accion.';
    END IF;

    IF p_monto_ajuste = 0 THEN
        RETURN TRUE; -- No hay cambio
    END IF;

    -- Asegurar registro
    PERFORM public.ensure_credito_contratante(p_id_contratante, p_moneda);

    -- Determinar operacion
    IF p_monto_ajuste > 0 THEN
        v_tipo_movimiento := 'ABONO';
        v_monto_absoluto := p_monto_ajuste;
    ELSE
        v_tipo_movimiento := 'CARGO';
        v_monto_absoluto := ABS(p_monto_ajuste);
    END IF;

    -- Bloquear y leer saldo actual
    SELECT "CreditoDisponibleEnUnidadMinima" INTO v_saldo_actual
    FROM public."CreditoXContratante"
    WHERE "IdContratante" = p_id_contratante
    FOR UPDATE;

    IF v_tipo_movimiento = 'CARGO' AND v_saldo_actual < v_monto_absoluto THEN
        RAISE EXCEPTION 'Saldo insuficiente. No se puede retirar % creditos del cliente (Saldo: %).', v_monto_absoluto, v_saldo_actual;
    END IF;

    -- Actualizar saldo
    UPDATE public."CreditoXContratante"
    SET "CreditoDisponibleEnUnidadMinima" = "CreditoDisponibleEnUnidadMinima" + p_monto_ajuste,
        "UpdatedAt" = NOW()
    WHERE "IdContratante" = p_id_contratante;

    -- Registrar transaccion de auditoria
    PERFORM public.registrar_tx_credito(
        p_id_contratante,
        v_tipo_movimiento,
        'AJUSTE_SUPERADMIN',
        v_monto_absoluto,
        p_moneda,
        NULL,
        NULL,
        'AJUSTE-SA-' || EXTRACT(EPOCH FROM NOW())::BIGINT,
        jsonb_build_object('ejecutado_por', auth.uid(), 'monto_neto', p_monto_ajuste)
    );

    RETURN TRUE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Permisos al RPC
GRANT EXECUTE ON FUNCTION public.ajustar_credito_superadmin(UUID, BIGINT, CHAR) TO authenticated;

COMMIT;
