
-- ==============================================================================
-- SCRIPT DE INICIALIZACIÓN SUPABASE - PROYECTO: NOTIFICAPE
-- Dialecto: PostgreSQL
-- Nota: Se usan comillas dobles ("") para forzar el PascalCase/CamelCase
-- requerido por la convención del Developer.
-- ==============================================================================

-- 1. EXTENSIONES
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==========================================
-- 2. CATÁLOGOS BASE
-- ==========================================

CREATE TABLE public."Licencias" (
    "IdLicencia" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Nombre" VARCHAR(50) NOT NULL,
    "LimiteDispositivos" INT DEFAULT 1,
    "LimiteUsuarios" INT NOT NULL,
    "PrecioCentimos" INT NOT NULL,
    "Moneda" VARCHAR(3) DEFAULT 'PEN',
    "DuracionDias" INT NOT NULL DEFAULT 30,
    "SkuExterno" VARCHAR(50) UNIQUE NOT NULL,
    "Activo" BOOLEAN DEFAULT TRUE
);

CREATE TABLE public."Billeteras" (
    "IdBilletera" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PackageName" VARCHAR(100) UNIQUE NOT NULL,
    "Nombre" VARCHAR(50) NOT NULL
);

CREATE TABLE public."EstadosAuth" (
    "IdEstadoAuth" SMALLINT PRIMARY KEY,
    "NomEstaAuth" VARCHAR(20) NOT NULL
);

CREATE TABLE public."Roles" (
    "IdRol" SMALLINT PRIMARY KEY,
    "NomRol" VARCHAR(20) NOT NULL,
    "CanRead" BOOLEAN NOT NULL,
    "CanWrite" BOOLEAN NOT NULL
);

CREATE TABLE public."FiltrosXBilletera" (
    "IdFiltroBil" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IdBilletera" SMALLINT REFERENCES public."Billeteras"("IdBilletera") ON DELETE CASCADE,
    "NombreRegla" VARCHAR(50) NOT NULL,
    "RegexContenido" TEXT NOT NULL
);

-- ==========================================
-- 3. IDENTIDAD Y AUDITORÍA DE COMPRAS
-- ==========================================

CREATE TABLE public."Contratantes" (
    "IdContratante" UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    "NombreCompleto" VARCHAR(150) NOT NULL,
    "NombreNegocio" VARCHAR(100),
    "Correo" VARCHAR(100) UNIQUE NOT NULL,
    "TelefonoContratante" VARCHAR(20),
    "FechaCreacion" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public."Usuarios" (
    "IdUsuario" UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    "IdRol" SMALLINT REFERENCES public."Roles"("IdRol"),
    "NombreCompleto" VARCHAR(150) NOT NULL,
    "Correo" VARCHAR(100) UNIQUE NOT NULL,
    "TelefonoUsuario" VARCHAR(20),
    "EquipoMarca" VARCHAR(50),
    "EquipoModelo" VARCHAR(50),
    "FechaCreacion" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public."OrdenesCompra" (
    "NumeroOrden" VARCHAR(50) PRIMARY KEY,
    "PlataformaOrigen" VARCHAR(50) NOT NULL,
    "IdContratante" UUID REFERENCES public."Contratantes"("IdContratante") ON DELETE CASCADE,
    "FechaCanje" TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 4. INVENTARIO PREPAGO
-- ==========================================

CREATE TABLE public."LicenciasXContratante" (
    "IdLicenciaContratante" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IdContratante" UUID REFERENCES public."Contratantes"("IdContratante") ON DELETE CASCADE,
    "IdLicencia" SMALLINT REFERENCES public."Licencias"("IdLicencia"),
    "NumeroOrden" VARCHAR(50) REFERENCES public."OrdenesCompra"("NumeroOrden"),
    "DispositivoAsignado" UUID, -- NULL = Disponible en inventario
    "FechaAsignacion" TIMESTAMPTZ
);

-- ==========================================
-- 5. HARDWARE Y CONFIGURACIÓN
-- ==========================================

CREATE TABLE public."DispositivosXContratante" (
    "IdDispositivo" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "HardwareId" VARCHAR(100) UNIQUE,
    "IdContratante" UUID REFERENCES public."Contratantes"("IdContratante") ON DELETE CASCADE,
    "IdLicencia" SMALLINT REFERENCES public."Licencias"("IdLicencia"),
    "AliasDispositivo" VARCHAR(50) NOT NULL,
    "CodigoAcceso" VARCHAR(10) UNIQUE NOT NULL,
    "EquipoMarca" VARCHAR(50),
    "EquipoModelo" VARCHAR(50),
    "TelefonoDispositivo" VARCHAR(20),
    "FechaVencimiento" TIMESTAMPTZ, -- Permitimos NULL inicial
    "IsConnected" BOOLEAN DEFAULT FALSE,
    "Activo" BOOLEAN DEFAULT TRUE,
    "FechaReg" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public."BilleterasXDispositivo" (
    "IdDispositivo" UUID REFERENCES public."DispositivosXContratante"("IdDispositivo") ON DELETE CASCADE,
    "IdBilletera" SMALLINT REFERENCES public."Billeteras"("IdBilletera") ON DELETE CASCADE,
    "UrlQrPago" VARCHAR(255),
    "Activo" BOOLEAN DEFAULT TRUE,
    PRIMARY KEY ("IdDispositivo", "IdBilletera")
);

-- ==========================================
-- 6. AUTORIZACIÓN Y TRANSACCIONALIDAD
-- ==========================================

CREATE TABLE public."AutorizacionesXUsuario" (
    "IdAutorizacion" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IdDispositivo" UUID REFERENCES public."DispositivosXContratante"("IdDispositivo") ON DELETE CASCADE,
    "IdUsuario" UUID REFERENCES public."Usuarios"("IdUsuario") ON DELETE CASCADE,
    "IdEstadoAuth" SMALLINT REFERENCES public."EstadosAuth"("IdEstadoAuth"),
    "FechRegist" TIMESTAMPTZ DEFAULT NOW(),
    "IsConnected" BOOLEAN DEFAULT FALSE,
    "Observacion" VARCHAR(255)
);

CREATE TABLE public."NotificacionesXDispositivo" (
    "IdSync" UUID PRIMARY KEY,
    "SecuenciaLocal" BIGINT GENERATED ALWAYS AS IDENTITY,
    "IdDispositivo" UUID REFERENCES public."DispositivosXContratante"("IdDispositivo") ON DELETE CASCADE,
    "IdContratante" UUID REFERENCES public."Contratantes"("IdContratante") ON DELETE CASCADE,
    "IdBilletera" SMALLINT REFERENCES public."Billeteras"("IdBilletera"),
    "ContenidoMsg" VARCHAR(500) NOT NULL,
    "MontoCentimos" INT NOT NULL,
    "Moneda" VARCHAR(3) DEFAULT 'PEN',
    "Remitente" VARCHAR(100),
    "Privada" BOOLEAN DEFAULT FALSE,
    "Prueba" BOOLEAN DEFAULT FALSE,
    "FechaOpera" TIMESTAMPTZ NOT NULL,
    "EstadoProgreso" VARCHAR(20) DEFAULT 'PENDIENTE', -- PENDIENTE, REVISION, COMPLETADO, CERRADO
    "ContadorReclamaciones" INT DEFAULT 0,
    "IdUsuarioGanador" UUID REFERENCES public."Usuarios"("IdUsuario")
);

CREATE TABLE public."NotificacionesAUsuarios" (
    "IdSync" UUID REFERENCES public."NotificacionesXDispositivo"("IdSync") ON DELETE CASCADE,
    "IdUsuario" UUID REFERENCES public."Usuarios"("IdUsuario"),
    "FechaReg" TIMESTAMPTZ DEFAULT NOW(),
    "Observacion" TEXT,
    "EstadoReclamacion" VARCHAR(20) DEFAULT 'PROCESANDO',
    PRIMARY KEY ("IdSync", "IdUsuario")
);

-- ==========================================
-- 7. ÍNDICES DE RENDIMIENTO (B-TREE)
-- ==========================================

CREATE INDEX "idx_notif_caja_diaria" ON public."NotificacionesXDispositivo" ("IdDispositivo", "FechaOpera" DESC);
CREATE INDEX "idx_notif_reporte_gerencial" ON public."NotificacionesXDispositivo" ("IdContratante", "FechaOpera" DESC);
