-- ==========================================================
-- 6. RLS: AUDITORIA DE COMPRAS E IDENTIDAD
-- Permite que los Contratantes puedan crearse a sí mismos y
-- reclamar/registrar sus compras u órdenes de prueba.
-- ==========================================================

-- Habilitamos seguridad si es que previamente se activó desde UI
ALTER TABLE public."OrdenesCompra" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Contratantes" ENABLE ROW LEVEL SECURITY;

-- 6.1. Contratantes pueden registrar e inicializar sus propias órdenes
CREATE POLICY "Contratantes dueños de sus propias Ordenes" 
ON public."OrdenesCompra"
FOR ALL 
USING (auth.uid() = "IdContratante");

-- 6.2. Contratantes pueden crearse y ver su propio Perfil empresarial
CREATE POLICY "Contratantes dueños de su propio Perfil" 
ON public."Contratantes"
FOR ALL 
USING (auth.uid() = "IdContratante");


-- ==========================================================================
-- EXTENSIÓN (App Viewer): Origen -> 19_cambios_viewer_onboarding.sql
-- Porqué: Integrado durante auditoría por cruce de dominio (Tabla: Contratantes)
-- ==========================================================================

-- ==============================================================================
-- SCRIPT DE ACTUALIZACIÓN - NOTIFICAPE VIEWER (ONBOARDING Y CONFLICTOS)
-- ==============================================================================

-- 1. ACTUALIZACIÓN DE CONTRATANTES
-- Hacer el NombreNegocio único para permitir la búsqueda por nombre.
ALTER TABLE public."Contratantes"
ADD CONSTRAINT "unique_NombreNegocio" UNIQUE ("NombreNegocio");

-- 2. ACTUALIZACIÓN DE USUARIOS (ONBOARDING)
-- Añadir campos para perfil limpio del vendedor.
-- Nota: Se usará "NombreCompleto" (ya existente) como identificador principal.
ALTER TABLE public."Usuarios"
ADD COLUMN "FotoUrl" TEXT;

-- 3. ACTUALIZACIÓN DE NOTIFICACIONES (ESTADOS)
-- Añadir estado de progreso para gestión de asignaciones y conflictos.
-- 0: Pendiente, 1: Asignada, 2: En Conflicto, 3: Validada
ALTER TABLE public."NotificacionesXDispositivo"
ADD COLUMN "EstadoProgreso" SMALLINT DEFAULT 0;

-- 4. CREACIÓN DE TABLA DE CONFLICTOS
CREATE TABLE IF NOT EXISTS public."ConflictosXNotificacion" (
    "IdConflicto" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IdSync" UUID REFERENCES public."NotificacionesXDispositivo"("IdSync") ON DELETE CASCADE,
    "IdUsuarioReporta" UUID REFERENCES public."Usuarios"("IdUsuario") ON DELETE CASCADE,
    "Observacion" TEXT NOT NULL,
    "FechaReporte" TIMESTAMPTZ DEFAULT NOW(),
    "Resuelto" BOOLEAN DEFAULT FALSE,
    "IdUsuarioResuelve" UUID REFERENCES public."Usuarios"("IdUsuario"), -- Admin o Supervisor que resuelve
    "FechaResolucion" TIMESTAMPTZ
);

-- 5. POLÍTICAS RLS BÁSICAS PARA CONFLICTOS (Borrador inicial)
ALTER TABLE public."ConflictosXNotificacion" ENABLE ROW LEVEL SECURITY;

-- Los vendedores pueden crear conflictos si están autorizados en el dispositivo de la notificación
CREATE POLICY "Vendedores pueden reportar conflictos" ON public."ConflictosXNotificacion"
FOR INSERT WITH CHECK (
    EXISTS (
        SELECT 1 FROM public."NotificacionesXDispositivo" n
        JOIN public."AutorizacionesXUsuario" a ON n."IdDispositivo" = a."IdDispositivo"
        WHERE n."IdSync" = public."ConflictosXNotificacion"."IdSync"
        AND a."IdUsuario" = auth.uid()
        AND a."IdEstadoAuth" = 1 -- Aprobado
    )
);

-- Los vendedores pueden ver los conflictos de las notificaciones a las que tienen acceso
CREATE POLICY "Vendedores pueden ver sus conflictos" ON public."ConflictosXNotificacion"
FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM public."NotificacionesXDispositivo" n
        JOIN public."AutorizacionesXUsuario" a ON n."IdDispositivo" = a."IdDispositivo"
        WHERE n."IdSync" = public."ConflictosXNotificacion"."IdSync"
        AND a."IdUsuario" = auth.uid()
    )
);

